server:
  port: 8081
camunda.bpm:
  database:
    type: postgres
  job-execution:
    deployment-aware: true
    core-pool-size: 3
    max-pool-size: 15
    max-jobs-per-acquisition: 3
    wait-time-in-millis: 500
    lock-time-in-millis: 300000
    max-backoff: 150
    max-wait: 50
com:
  camunda:
    datasource:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password:
      driverClassName: org.postgresql.Driver
      poolName: camunda-pool